[package]
name = "lib_xlsx_img_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.14.1"
read_input = "0.8.6"
anyhow = "1"
zip = "0.6"
derive_more = "0.99.17"
thiserror = "1"