[package]
name = "lib_xlsx_img_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.18"
zip = "0.6"
thiserror = "1"